In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("yield_df.csv")

In [3]:
df.head()

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [4]:
df.shape

(28242, 8)

In [5]:
df=df.drop("Unnamed: 0", axis=1)

In [6]:
df.head()

,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [10]:
df = df.rename(columns={
    "hg/ha_yield": "yield",
    "average_rain_fall_mm_per_year": "rainfall",
    "pesticides_tonnes": "pesticides",
    "avg_temp": "temperature"
})

In [11]:
df.head()

      Area         Item  Year  yield  rainfall  pesticides  temperature
0  Albania        Maize  1990  36613    1485.0       121.0        16.37
1  Albania     Potatoes  1990  66667    1485.0       121.0        16.37
2  Albania  Rice, paddy  1990  23333    1485.0       121.0        16.37
3  Albania      Sorghum  1990  12500    1485.0       121.0        16.37
4  Albania     Soybeans  1990   7000    1485.0       121.0        16.37

In [12]:
df.columns

Index(['Area', 'Item', 'Year', 'yield', 'rainfall', 'pesticides',
       'temperature'],
      dtype='object')

In [13]:
df.isnull().sum()

Area           0
Item           0
Year           0
yield          0
rainfall       0
pesticides     0
temperature    0
dtype: int64

In [14]:
df.head()

      Area         Item  Year  yield  rainfall  pesticides  temperature
0  Albania        Maize  1990  36613    1485.0       121.0        16.37
1  Albania     Potatoes  1990  66667    1485.0       121.0        16.37
2  Albania  Rice, paddy  1990  23333    1485.0       121.0        16.37
3  Albania      Sorghum  1990  12500    1485.0       121.0        16.37
4  Albania     Soybeans  1990   7000    1485.0       121.0        16.37

In [15]:
df.columns

Index(['Area', 'Item', 'Year', 'yield', 'rainfall', 'pesticides',
       'temperature'],
      dtype='object')

In [19]:
print("Number of countries:", df["Area"].nunique())
print("Number of crops:", df["Item"].nunique())

Number of countries: 101
Number of crops: 10

In [20]:
df["Item"].unique()

array(['Maize', 'Potatoes', 'Rice, paddy', 'Sorghum', 'Soybeans', 'Wheat',
       'Cassava', 'Sweet potatoes', 'Plantains and others', 'Yams'],
      dtype=object)

In [21]:
df["Area"].unique()[:20]

array(['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Belarus', 'Belgium', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada'],
      dtype=object)

Encode categorical features

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
area_encoder = LabelEncoder()
item_encoder = LabelEncoder()

In [26]:
df["Area"] = area_encoder.fit_transform(df["Area"])
df["Item"] = item_encoder.fit_transform(df["Item"])

In [27]:
df.head()

   Area  Item  Year  yield  rainfall  pesticides  temperature
0     0     1  1990  36613    1485.0       121.0        16.37
1     0     3  1990  66667    1485.0       121.0        16.37
2     0     4  1990  23333    1485.0       121.0        16.37
3     0     5  1990  12500    1485.0       121.0        16.37
4     0     6  1990   7000    1485.0       121.0        16.37

In [28]:
df.dtypes

Area             int64
Item             int64
Year             int64
yield            int64
rainfall       float64
pesticides     float64
temperature    float64
dtype: object

In [29]:
X = df.drop("yield", axis=1)
y = df["yield"]

In [31]:
print(X.shape)
print(y.shape)

(28242, 6)
(28242,)

In [32]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test, y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [35]:
print(X_train.shape)
print(X_test.shape)

(22593, 6)
(5649, 6)

In [39]:
print(X.shape)
print(y.shape)

(28242, 6)
(28242,)

In [46]:
df.to_csv("final_yeild_dataset.csv", index=False)

In [47]:
import pickle

with open("area_encoder.pkl", "wb") as f:
    pickle.dump(area_encoder, f)

with open("item_encoder.pkl", "wb") as f:
    pickle.dump(item_encoder, f)